export const abs = (x: number) => Math.abs(x);
export const round = (x: number) => Math.round(x);
export const ceil = (x: number) => Math.ceil(x);
export const floor = (x: number) => Math.floor(x);
export const max = (...nums: number[]) => Math.max(...nums);
export const min = (...nums: number[]) => Math.min(...nums);
export const exp = (x: number) => Math.exp(x);
export const pow = (base: number, exp: number) => Math.pow(base, exp);
export const sqrt = (x: number) => Math.sqrt(x);
export const log = (x: number) => Math.log(x);
export const log10 = (x: number) => Math.log10(x);
export const sin = (x: number) => Math.sin(x);
export const cos = (x: number) => Math.cos(x);
export const tan = (x: number) => Math.tan(x);
export const asin = (x: number) => Math.asin(x);
export const acos = (x: number) => Math.acos(x);
export const atan = (x: number) => Math.atan(x);
export const sinh = (x: number) => Math.sinh(x);
export const cosh = (x: number) => Math.cosh(x);
export const tanh = (x: number) => Math.tanh(x);
export const random = () => Math.random();
